######################################################################
# Automatically generated by qmake (2.01a) Wed May 29 00:08:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h SplinesCalculator.h LineEdit.h
SOURCES += main.cpp MainWindow.cpp SplinesCalculator.cpp LineEdit.cpp
TRANSLATIONS += splines_bg.ts
