######################################################################
# Automatically generated by qmake (2.01a) Thu May 2 22:27:03 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
